jobs:
  build:
    docker:
      - image: circleci/node:10.15-stretch-browsers
    working_directory: ~/project/
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: npm install
      - run:
          name: 'Check'
          command: npm run check
      - run:
          name: 'Test'
          command: npm run test
      - run:
          name: 'Push to UXPin if branch is master'
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]
            ./node_modules/.bin/uxpin-merge push \
              --webpack-config ./webpack.config.js \
              --wrapper ./src/UXPinWrapper/UXPinWrapper.js
            fi
